- name: Smoke test
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Hello
      ansible.builtin.debug:
        msg: "Ansible is working"
    - name: Hello2
      ansible.builtin.debug:
        msg: "Ansible is working 2"
