---
- name: Add Node Yum repo
  yum_repository:
    name: nodesource-nodejs
    description: Node.js Packages
    baseurl: https://rpm.nodesource.com/pub_23.x/nodistro/nodejs/x86_64
    gpgkey: https://rpm.nodesource.com/gpgkey/ns-operations-public.key

- name: Install Node.js
  yum:
    name: nodejs
    state: present

- name: Copy sample app
  copy:
    src: app.js
    dest: /home/ec2-user/app.js
    owner: ec2-user

- name: Start sample app
  shell: nohup node /home/ec2-user/app.js &
  args:
    chdir: /home/ec2-user